Fix the get upload options exhaustive memory usage
If the $submissioncount parameter was null, this caused an endless loop
until the memory limit is reached. The function was updated to prevent
this behavior.

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to
allocate 167772160 bytes) in
/var/www/html/mod/assign/submission/external_server/classes/helper.php
on line 100
```